<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('New Project'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <header>
            <nav class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('index') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Application') ?></a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="<?php echo $this->url('index') ?>"><?php echo $this->translate('Home') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('post') ?>"><?php echo $this->translate('Post') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('about-us') ?>"><?php echo $this->translate('About us') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Contact') ?></a></li>
                            <li class="active"><a href="<?php echo $this->url('auth') ?>"><?php echo $this->translate('Login') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>
        </header>
        <section>
            <div class="container">
                <?php echo $this->content; ?>
            </div>
            
        </section>
        <footer>
            <div class="container">
                <hr>
                <p class="text-center">&copy; 2005 - <?php echo date('Y') ?> by Zend Framework Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
            
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>