<?php 
$title = 'My Training';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th> ID</th>
				<th> NAME</th>
				<th> VALUE</th>
				<th><a type="button" class="btn btn-primary" href="<?php echo $this->url('training/add',array());?>">Add New</a></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->paginators as $training):?>
			<tr>
				<td><?php echo $this->escapeHtml($training->id);?></td>
				<td><?php echo $this->escapeHtml($training->name);?></td>
				<td><?php echo $this->escapeHtml($training->value);?></td>
				<td>
					<a type="button" class="btn btn-success" href="<?php echo $this->url('training/edit',array('id' => $training->id));?>">Edit</a>
					<a type="button" class="btn btn-danger" href="<?php echo $this->url('training/delete',
            array('id' => $training->id));?>">Delete</a>
				</td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<?php 
echo $this->paginationControl(
     $this->paginators,
     'sliding',
     'paginator/paginator.phtml',
     array(
         'route' => 'training/list'
     )
 ); 
?>